### ISSUE TITLE
exception in TriangleDemo.cpp

### ISSUE THREAD

**Issue by MeryamM213** [GiuliaXR/HeroOfTheTelliverse#3]
on line 37 there is an exception which is thrown when the game is exited. It appears to be some form of access violation. Changing member to protected and adding a try catch did not prevent the error. 

possible fixes:
set member to public
![scrn1](https://user-images.githubusercontent.com/36249159/48728795-e1285380-ec2d-11e8-8d9c-9a4a2bf77744.JPG)

**Comment by thecubist** [comment]
Fixed the issue by moving the object release up. The problem was caused by parent classes being de-referenced before the colour texture variable was released
